### ISSUE TITLE
How to check "Websocket Support" and update the default config of nginx

### ISSUE THREAD

**Issue by abs0lom** [caprover/one-click-apps#101]
Hello,

I'm want to create a [collabora](https://www.collaboraoffice.com/code/) one-click-app.

I have a handmade instance running on my caprover.

During the configuration, I had to activate the websockets and add the instruction `proxy_read_timeout 36000s` in the nginx configuration.

* Which fields do I need to add to activate websockets?

* For the custom configuration of the nginx, is there a way to do this in the template or do I have to specify this step in the end instructions?

Tank you for your great job !

**Comment by githubsaturn** [comment]
Unforutnately, there is not support for the WebSocket and custom config options in one-click apps. They can be added to the end instructions for now. Feel free to open a feature request on the main repo for the websocket flag on one-click app. For the nginx customization, I can't think of a clean way to do this. So that part will always have to be done manually.

**Comment by abs0lom** [comment]
Thank you for your answer, I'm going to do it this way.
