### ISSUE TITLE
Chatwoot - SMTP email does not work with environment variables

### ISSUE THREAD

**Issue by Brandutchmen** [caprover/one-click-apps#180]
Has anyone found a way to solve this? I have tried:
`openssl_verify_mode=VERIFY_NONE`
`openssl_verify_mode=SSL`
`openssl_verify_mode=NONE`
`SMTP_ENABLE_STARTTLS_AUTO=true`

**Comment by githubsaturn** [comment]
@Brandutchmen it's better to ask the app specific questions in related forums. For example, Chatwood one click app is just using official Chatwood Docker image. You can ask your question in Chatwood issues:

https://github.com/chatwoot/chatwoot

**Comment by eashman** [comment]
Actually, the issue is the way the config for Caprover works.  They don't prompt you for the SMTP info on install, and as a result, the SMTP variables don't end up in the chatwoot-worker app.

You have to put those variables there too, manually, after installation.

I would recommend they prompt for the SMTP vars during install so both apps get that.

Alternatively, there might be a nice way to do "grouping" of apps in a future Caprover that shares Env vars.  That would be a nice feature.

**Comment by yagoveloso** [comment]
If you’re encountering issues with Chatwoot sending emails via sendmail instead of SendGrid, especially when using EasyPanel, it’s essential to ensure that the environment variables are correctly set for both the main application and the Sidekiq worker. Here’s a step-by-step guide to address this:
	1.	Set Environment Variables for the Main Application:
	•	In EasyPanel, navigate to your Chatwoot application settings.
	•	Add the following environment variables: ￼

SMTP_ADDRESS=smtp.sendgrid.net
SMTP_PORT=587
SMTP_DOMAIN=your_verified_domain.com
SMTP_USERNAME=apikey
SMTP_PASSWORD=your_sendgrid_api_key
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

Replace your_verified_domain.com with your actual domain and your_sendgrid_api_key with the API key from SendGrid. Ensure that SMTP_USERNAME is set to apikey, as required by SendGrid.

	2.	Configure Environment Variables for the Sidekiq Worker:
	•	In EasyPanel, locate the Sidekiq service associated with your Chatwoot application. ￼
	•	Add the same environment variables as above to the Sidekiq service. ￼
Note: Sidekiq processes background jobs in Chatwoot, including email deliveries. If the environment variables are not set for Sidekiq, it may default to using sendmail.
	3.	Restart Both Services:
	•	After setting the environment variables, restart both the main Chatwoot application and the Sidekiq worker to apply the changes.
	4.	Verify the Configuration:
	•	Send a test email through Chatwoot to ensure that emails are being sent via SendGrid. ￼
	•	Monitor the logs in EasyPanel for both the Chatwoot application and Sidekiq to check for any errors or misconfigurations.

By ensuring that both the main application and the Sidekiq worker have the correct environment variables set, Chatwoot should utilize SendGrid for email delivery as intended.

**Comment by yagoveloso** [comment]
If you’re encountering issues with Chatwoot sending emails via sendmail instead of SendGrid, especially when using EasyPanel, it’s essential to ensure that the environment variables are correctly set for both the main application and the Sidekiq worker. Here’s a step-by-step guide to address this:
1.	Set Environment Variables for the Main Application:
	•	In EasyPanel, navigate to your Chatwoot application settings.
	•	Add the following environment variables: ￼

SMTP_ADDRESS=smtp.sendgrid.net
SMTP_PORT=587
SMTP_DOMAIN=your_verified_domain.com
SMTP_USERNAME=apikey
SMTP_PASSWORD=your_sendgrid_api_key
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

Replace your_verified_domain.com with your actual domain and your_sendgrid_api_key with the API key from SendGrid. Ensure that SMTP_USERNAME is set to apikey, as required by SendGrid.

2.	Configure Environment Variables for the Sidekiq Worker:
	•	In EasyPanel, locate the Sidekiq service associated with your Chatwoot application. ￼
	•	Add the same environment variables as above to the Sidekiq service. ￼
Note: Sidekiq processes background jobs in Chatwoot, including email deliveries. If the environment variables are not set for Sidekiq, it may default to using sendmail.
3.	Restart Both Services:
	•	After setting the environment variables, restart both the main Chatwoot application and the Sidekiq worker to apply the changes.
4.	Verify the Configuration:
	•	Send a test email through Chatwoot to ensure that emails are being sent via SendGrid. ￼
	•	Monitor the logs in EasyPanel for both the Chatwoot application and Sidekiq to check for any errors or misconfigurations.

By ensuring that both the main application and the Sidekiq worker have the correct environment variables set, Chatwoot should utilize SendGrid for email delivery as intended.
