### ISSUE TITLE
App Suggestion: OpenVPN-AS

### ISSUE THREAD

**Issue by olla-dev** [caprover/one-click-apps#219]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
Have any open source vpn server like openvpn-as

**Do you know if there is any official Docker image for the app?**
there is a docker image from linuxserver (linuxserver/openvpn-as/)

**Comment by tomholford** [comment]
@m4200 FYI I have started a PR for this template, since I could also use a VPN :) Will update here when it's ready for review.

**Comment by tomholford** [comment]
update: per this comment from @githubsaturn, this app is not currently compatible with caprover

https://github.com/caprover/one-click-apps/pull/222#issuecomment-656083740

**Comment by dramikei** [comment]
Hi, sorry to bump an old issue. But it turns out this issue couldn't be resolved due to docker swarm not supporting capabilities at the time ( #222 )

Capabilities support was added for swarm in [Docker 20.10.0](https://github.com/docker/cli/pull/2687) which should allow us to port openvpn-as or even wireguard to Caprover.

But before that we will need to add support for caprover to parse `cap_add` parameter of docker-compose.yml, which probably is ignored currently as stated in `README.md`:

```
## Services

- Other than image, environment, ports, volumes, depends_on, and hostname, other parameters are currently being ignored by CapRover. If you need a particular parameter, please file an issue, and we'll add it to the respected list.
```

**Comment by dramikei** [comment]
Opened an issue in caprover repo regarding this: caprover/caprover#1100

**Comment by prakasharyaman** [comment]
Any updates on openVpn on Caprover ?
