### ISSUE TITLE
App Suggestion: PrivateBin

### ISSUE THREAD

**Issue by githubsaturn** [caprover/one-click-apps#226]
**Please tell us what app you'd like to see on CapRover as a one-click app.**
https://github.com/PrivateBin/PrivateBin

**Do you know if there is any official Docker image for the app?**
https://hub.docker.com/r/privatebin/nginx-fpm-alpine

**Comment by monkeydust** [comment]
second that.

**Comment by monkeydust** [comment]
tried deploying directly from docker get 502 error on web load. This in the logs. Any idea?


**
Logs:
$ sudo docker service logs srv-captain--privatebin --since 10m --follow
srv-captain--privatebin.1.qe9a9mr7fkmr@ip-172-26-1-135 | /
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/php-fpm7/run: Operation not permitted
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/nginx/run: Operation not permitted
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [s6-init] ensuring user provided files have correct perms...exited 0.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [fix-attrs.d] applying ownership & permissions fixes...
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [fix-attrs.d] done.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [cont-init.d] executing container initialization scripts...
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [cont-init.d] done.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [services.d] starting services
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | 2020/08/13 16:21:08 [warn] 181#181: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [services.d] done.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [13-Aug-2020 16:21:08] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [13-Aug-2020 16:21:08] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [13-Aug-2020 16:21:08] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [13-Aug-2020 16:21:08] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [13-Aug-2020 16:21:08] NOTICE: fpm is running, pid 182
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135 | [13-Aug-2020 16:21:08] NOTICE: ready to handle connections

Txs in advance

**Comment by zuedev** [comment]
@githubsaturn this was implemented in 7c827cac0e2acb4fb912fc51b89fc0562de3e459, cleanup? 😅

**Comment by githubsaturn** [comment]
Right!
