### ISSUE TITLE
[BUG] TSL/SSL Authentication error on poste.io

### ISSUE THREAD

**Issue by ethancedwards8** [caprover/one-click-apps#231]
```dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=xxx.xxx.xxx.xxx, lip=xxx.xxx.xxx.xxx, TLS handshaking: SSL_accept() failed: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca: SSL alert number 48```

Error when trying to connect POP3 or IMAP through the Thunderbird mail client. The issue is it doesn't make a connection behind the Caprover reverse proxy, the SSL certificate doesn't get set in Poste itself.

But this works if you turn authentication off, which for obvious reasons is less than ideal. If I request a certificate it doesn't work behind a reverse proxy.

**Comment by githubsaturn** [comment]
I believe this is due to the fact that poste.io tries to setup their own SSL certificates, which obviously cannot - as `./well-known` directory is being managed by CapRover because CapRover manages SSL certificates. You have two options:
- Let CapRover manage SSL certificates, and just import the SSL certificates and have poste.io use those.
To do this, you need to map `/captain/data/letencrypt` to `/my-certs` directory in poste.io and have poste.io use the relevant certificate.
- Second option is to block off CapRover from using `.well-known` path. This way, poste.io can request SSL certs and automatically use them. To do this, edit nginx config for your poste.io app and remove all usage of `./well-known`

**Comment by ethancedwards8** [comment]
Can I submit a PR on the poste.io app to make a note to do one of these?

**Comment by githubsaturn** [comment]
Sure! If you want you can write up a quick tutorial blog and link it in the docs too. I know poste is a complex app and confuses lots of folks

**Comment by laruche** [comment]
To close this Bug, a quick tutorial for Caprover One Click Install 

To Activate SSL/TLS in Poste.io 

In {your app}'s HTTP Settings, don't activate SSL on any domain, 
click on Edit Default NGINX Config AND remove thoses lines (present two times in the default config)

` Used by Lets Encrypt
     location /.well-known/acme-challenge/ {
       root <%-s.staticWebRoot%>;
      }`

After app reboot, go to : http://yourcustomedomain.com/admin 
And to : System Settings => TLS Certificate
Click on Add Let's Encrypt certificate
Execute Poste.io script 

Hope this tutorial help you :)

**Comment by githubsaturn** [comment]
Thanks a lot @laruche for the detailed guide.

**Comment by cr1s3c** [comment]
Is the first soluction still a working? My poste.io instance does not use the provided certificates and I added the persistant directory. Is there anything else I need to do for this to work?

**Comment by ethancedwards8** [comment]
I'm not sure, I stopped using Caprover months ago.

**Comment by gallynero** [comment]
> To close this Bug, a quick tutorial for Caprover One Click Install
> 
> ### To Activate SSL/TLS in Poste.io
> **Use Caprover let's encrypt method**
> 
> In **{your app}**'s HTTP Settings, activate SSL on your domain
> 
> In App Confg, add new folder in Persistent Directories
> 
> ![image](https://user-images.githubusercontent.com/1287795/97237997-ac917f00-17e8-11eb-9324-7a2bd39ff376.png)
> 
> TLS / SSL is now activated, and your mail's app can use it !
> 
> **If you want use Poste.io let's encrypt, but loose https acces to your domain **
> 
> In **{your app}**'s HTTP Settings, don't activate SSL on any domain,
> click on Edit Default NGINX Config AND remove thoses lines (present two times in the default config)
> 
> ` Used by Lets Encrypt`
> ` location /.well-known/acme-challenge/ {`
> ` root <%-s.staticWebRoot%>;`
> ` }`
> 
> After app reboot, go to : **http://yourcustomedomain.com/admin**
> And to : System Settings => TLS Certificate
> Click on Add Let's Encrypt certificate
> Execute Poste.io script
> 
> Hope this tutorial help you :)

This methods work actually?

I can't add any account to Gmail app because the certificate is invalid.

Thanks and regards.

**Comment by abir-taheer** [comment]
> > To close this Bug, a quick tutorial for Caprover One Click Install
> > ### To Activate SSL/TLS in Poste.io
> > **Use Caprover let's encrypt method**
> > In **{your app}**'s HTTP Settings, activate SSL on your domain
> > In App Confg, add new folder in Persistent Directories
> > ![image](https://user-images.githubusercontent.com/1287795/97237997-ac917f00-17e8-11eb-9324-7a2bd39ff376.png)
> > TLS / SSL is now activated, and your mail's app can use it !
> > **If you want use Poste.io let's encrypt, but loose https acces to your domain **
> > In **{your app}**'s HTTP Settings, don't activate SSL on any domain,
> > click on Edit Default NGINX Config AND remove thoses lines (present two times in the default config)
> > ` Used by Lets Encrypt`
> > ` location /.well-known/acme-challenge/ {`
> > ` root <%-s.staticWebRoot%>;`
> > ` }`
> > After app reboot, go to : **http://yourcustomedomain.com/admin**
> > And to : System Settings => TLS Certificate
> > Click on Add Let's Encrypt certificate
> > Execute Poste.io script
> > Hope this tutorial help you :)
> 
> This methods work actually?
> 
> I can't add any account to Gmail app because the certificate is invalid.
> 
> Thanks and regards.

The first method that @laruche  suggested didn't work for me but letting poste.io manage the ssl cert worked perfectly. You have to make sure that when you're commenting out the `.well-known` paths you comment them out in all places in the caprover nginx config.

**Comment by javanese84** [comment]
Yes, letting poste.io manage the certificate (method 2 that @laruche suggested) works.
But with that, you loose https access to webamil and admin. That isn't a very nice solution.

Did anyone get it to work with the caprover certificates?

**Comment by tomexx** [comment]
+1

**Comment by magandadigital** [comment]
> > > To close this Bug, a quick tutorial for Caprover One Click Install
> > > ### To Activate SSL/TLS in Poste.io
> > > **Use Caprover let's encrypt method**
> > > In **{your app}**'s HTTP Settings, activate SSL on your domain
> > > In App Confg, add new folder in Persistent Directories
> > > ![image](https://user-images.githubusercontent.com/1287795/97237997-ac917f00-17e8-11eb-9324-7a2bd39ff376.png)
> > > TLS / SSL is now activated, and your mail's app can use it !
> > > **If you want use Poste.io let's encrypt, but loose https acces to your domain **
> > > In **{your app}**'s HTTP Settings, don't activate SSL on any domain,
> > > click on Edit Default NGINX Config AND remove thoses lines (present two times in the default config)
> > > ` Used by Lets Encrypt`
> > > ` location /.well-known/acme-challenge/ {`
> > > ` root <%-s.staticWebRoot%>;`
> > > ` }`
> > > After app reboot, go to : **http://yourcustomedomain.com/admin**
> > > And to : System Settings => TLS Certificate
> > > Click on Add Let's Encrypt certificate
> > > Execute Poste.io script
> > > Hope this tutorial help you :)
> > 
> > 
> > This methods work actually?
> > I can't add any account to Gmail app because the certificate is invalid.
> > Thanks and regards.
> 
> The first method that @laruche suggested didn't work for me but letting poste.io manage the ssl cert worked perfectly. You have to make sure that when you're commenting out the `.well-known` paths you comment them out in all places in the caprover nginx config.

THANK YOU!!!! I had such a nightmare, I tried your method and it worked! I can now login with gmail and add my email accounts there with no problems at all. You're an angel.

**Comment by locvfx** [comment]
I use the first method, let caprover manage SSL. The advantage: admin dashboard and roundcude both benefit https
Let say you deploy an app called mail.MY-DOMAIN.COM

Steps:
1. Install one-click Poste App. Caprover will tell you to change nginx config : DONT FOLLOW (let caprover manage https)
2. Enable https, force https (in caprover panel), you will have https both admin dashboard and webmail 
<img width="361" alt="Screenshot 2023-11-10 at 9 37 48 AM" src="https://github.com/caprover/one-click-apps/assets/884997/43ac736d-fb06-4c10-b66b-c7b0db800475">
3. This is important, we need to map certificates ( which generated by Caprover (in step 2) ) to Poste App. The location of the Certificate in Poste App : **/data/ssl** this folder had been mount , we just simply copy our files and place (+rename) in the right location:

cp /captain/data/letencrypt/etc/live/mail.MY-DOMAIN.COM/privkey.pem /var/lib/docker/volumes/captain--mail.MY-DOMAIN.COM/_data/ssl/server.key
cp /captain/data/letencrypt/etc/live/chain.pem /var/lib/docker/volumes/captain--mail.MY-DOMAIN.COM/_data/ssl/ca.crt
cp /captain/data/letencrypt/etc/live/cert.pem /var/lib/docker/volumes/captain--mail.MY-DOMAIN.COM/_data/ssl/server.crt

(please change mail.MY-DOMAIN.COM accordingly)
Now you can test whether the certificate works properly, use Gmail App to login or SMTP wordpres plugin to send email via port 587

If all works well, then me must renew certificate process automatically everytime caprover renew certificates. Because the files in this folder : /captain/data/letencrypt/etc/live/mail.MY-DOMAIN.COM/*   are symbolic links , not an actualy files
<img width="987" alt="Screenshot 2023-11-10 at 9 31 55 AM" src="https://github.com/caprover/one-click-apps/assets/884997/133a2131-215b-4092-8f4e-01bce5742625">
Maybe we make a shell script and put those commands above inside, set cron everyday to automate the copy process.

Congratulate, you did it.
