### ISSUE TITLE
App issue: focalboard embeds spyware

### ISSUE THREAD

**Issue by sneak** [caprover/one-click-apps#612]
Focalboard, like Mattermost, embeds silent, nonconsensual, phone-home spyware by default.  (It's made by the same people as Mattermost.)

The mattermost OCA template patches this out automatically, but the Focalboard one does not.

This is a tracking issue - I intend to send a PR to fix this (as I did when I created the Mattermost OCA template) soon.

**Comment by githubsaturn** [comment]
You've made great contributions to the project and I thank you for that. But please refrain from using Spyware term for analytics purposes. CapRover is simply an app store, just a glorified version of Dockerhub with simple installers. The language that you're using here indicates that these software are malware. 

In your privacy-concerning view, 99% of the software on the internet are malware because they're using analytics. 

You are more than welcome to create a privacy-restricted clone of one click apps and make modifications there. I understand that you are a privacy activist, but I am spending hundreds of hours of my time for free to maintain health of this project and I do not want to see this type of language being used here. 

Like I said, you are encouraged to fork the repo and make a specific version of this for yourself. Pretty sure there are tens, if not hundreds of other apps in this repo that do use some sort of analytics and I do not want to concern myself with patching them one by one. Specifically the type of patching that you applied to Mattermost might cause issues since you're just blocking security update domains completely.

Anyways, like I said, please feel free to fork the repo and use your own (I think you mentioned you already do this). But please do not use the term Spyware for analytics.

**Comment by sneak** [comment]
The term spyware is an objectively accurate description of software that transmits the user's activities off their device without their knowledge or consent.  I have no problem with analytics - I have a problem with *nonconsensual* analytics.

It's not just me: many software packagers/distributors do this.  For example, Debian maintainers (which are just a glorified tarball, really ;) ) remove this sort of spyware when they package software for distribution.  It's a normal thing for people who package software distributions to do.

I'm not going to take up any of your time, and, actually, I'm not an activist - I just like to use the correct terms to describe things.  If I were an activist, I would be doing things in the industry to try to get people to stop shipping nonconsensual spyware.  I'm not, I'm just working to patch it out for users on a case-by-case basis, like I did in the Mattermost OCA (and will continue to do in other apps when and where I see it).

The changes in Mattermost don't cause issues; I didn't block a security update domain, I blocked a security update *notification* domain, which is something different.  It doesn't distribute software, it receives queries that the user didn't choose to send.

**Comment by githubsaturn** [comment]
> If I were an activist, I would be doing things in the industry to try to get people to stop shipping nonconsensual spyware

The term Spyware is almost exclusively used by you WRT Mattermost. You are actively raising awareness against these dark patterns. Also, it's primarily what you post on HN. Being a privacy activist is a positive thing, you should be proud of what you do. I'm not labeling it as a negative factor, just saying what I have observed.

![image](https://user-images.githubusercontent.com/10582082/150688609-6ae1c4af-7378-42b3-a762-a2a80c912063.png)
![image](https://user-images.githubusercontent.com/10582082/150688655-74c838b0-7ad3-4657-8b14-5977e894323b.png)


> The changes in Mattermost don't cause issues; I didn't block a security update domain, I blocked a security update notification domain, which is something different. It doesn't distribute software, it receives queries that the user didn't choose to send.

> remove this sort of spyware when they package software for distribution

NPM in the background checks for updates. Is this a spyware too? It transmits your IP.... It hasn't been removed from the store.

**Comment by githubsaturn** [comment]
Having said that, CapRover definitely lacks a proper T&C and PP. I'll be adding these in the future to remove any confusion.

**Comment by sneak** [comment]
It seems to me that caprover isn't a service, but is simply open source, free software. 

Does it really need terms and conditions beyond the license?  Linux doesn't have terms and conditions or a privacy policy, you just get the software and it has a license.

**Comment by githubsaturn** [comment]
You're correct. But two things. First, there will be paid premium features in the future (that might actually have a separate T&C... mostly for enterprise users...). Second, the app store itself can be viewed at as a service. I want to make sure to outline the T&C. Dependency on DockerHub, Github, etc... It is mentioned in the docs, but an separate doc would probably serve better. Also, I want to explicitly call out that CapRover takes no responsibility for the add-ons / OCAs. Basically the "as-is" part of apache license, but more explicit. 

![image](https://user-images.githubusercontent.com/10582082/150887303-d7a08987-2577-4677-8075-a3de7769f8c5.png)
