### ISSUE TITLE
App issue: [Penpot]

### ISSUE THREAD

**Issue by matbgn** [caprover/one-click-apps#942]
Based on selected app name `penpot` and last version 1.18.4 I suspect a nginx error based on Caprover subtleties, see below. Any help will be appreciated ;-)

Error in console
```
2023-06-02T08:24:31.156882691Z 2023/06/02 08:24:31 [emerg] 1#1: host not found in upstream "penpot-backend" in /etc/nginx/nginx.conf:85
2023-06-02T08:24:31.156974173Z nginx: [emerg] host not found in upstream "penpot-backend" in /etc/nginx/nginx.conf:85
```

Surely incompatibilities coming from newer version of penpot and the use of Caprover Extra trick till now:

```
...
        caproverExtra:
            dockerfileLines:
                - FROM penpotapp/frontend:$$cap_penpot_frontend_version
                - RUN sed -i 's/penpot-backend/srv-captain--$$cap_appname-backend/g' /etc/nginx/nginx.conf
                - RUN sed -i 's/penpot-exporter/srv-captain--$$cap_appname-exporter/g' /etc/nginx/nginx.conf
...
```

**Comment by kisamoto** [comment]
Looking at the [penpot nginx script](https://github.com/penpot/penpot/blob/develop/docker/images/files/nginx-entrypoint.sh), it only creates the nginx.conf upon image startup which is why the caprover `sed` doesn't take place. 

However you can see it now accepts some environment variables for the Backend and Exporter URIs.

Until this is fixed in the one-click apps (I'll submit a PR if I have time) you can add the relevant environment variables to your `penpot` config (see attached screenshot - obviously update with your `cap_appname`). This will fix the nginx error upon startup.

```bash
PENPOT_BACKEND_URI=http://srv-captain--penpot-backend:6060
PENPOT_EXPORTER_URI=http://srv-captain--penpot-exporter:6061
```

![image](https://github.com/caprover/one-click-apps/assets/1744908/9d4f1715-c6b0-44c6-9c65-f0b7441aae88)

**Comment by matbgn** [comment]
I was getting this way but completly messed up. Thank you a lot.
